/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account-verified`; params?: Router.UnknownInputParams; } | { pathname: `/creator-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/form-creator`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/otp-verification`; params?: Router.UnknownInputParams; } | { pathname: `/register-creator`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/account-verified`; params?: Router.UnknownOutputParams; } | { pathname: `/creator-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/form-creator`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/otp-verification`; params?: Router.UnknownOutputParams; } | { pathname: `/register-creator`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/account-verified${`?${string}` | `#${string}` | ''}` | `/creator-dashboard${`?${string}` | `#${string}` | ''}` | `/form-creator${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/otp-verification${`?${string}` | `#${string}` | ''}` | `/register-creator${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account-verified`; params?: Router.UnknownInputParams; } | { pathname: `/creator-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/form-creator`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/otp-verification`; params?: Router.UnknownInputParams; } | { pathname: `/register-creator`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
